# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

# Υλοποιήσεις μέσω BinarySearchTree: ADTSet
#
UsingBinarySearchTree_ADTSet_test_OBJS  = ADTSet_test.o $(MODULES)/UsingBinarySearchTree/ADTSet.o

# Υλοποιήσεις μέσω AVL Tree: ADTSet
#
UsingAVL_ADTSet_test_OBJS  = ADTSet_test.o $(MODULES)/UsingAVL/ADTSet.o

# Υλοποιήσεις μέσω B Tree: ADTSet
#
UsingBTree_ADTSet_test_OBJS  = ADTSet_test.o $(MODULES)/UsingBTree/ADTSet.o

# Ο βασικός κορμός του Makefile
include ../common.mk