# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

# Υλοποιήσεις μέσω HashTable: ADTMap
#
UsingHashTable_ADTMap_test_OBJS		= ADTMap_test.o $(MODULES)/UsingHashTable/ADTMap.o

# Υλοποιήσεις μέσω CuckooHash: ADTMap
#
UsingCuckooHash_ADTMap_test_OBJS	= ADTMap_test.o $(MODULES)/UsingCuckooHash/ADTMap.o

# Υλοποιήσεις μέσω HashWithSet: ADTMap
#
UsingHashWithSet_ADTMap_test_OBJS	= ADTMap_test.o $(MODULES)/UsingHashWithSet/ADTMap.o $(MODULES)/UsingAVL/ADTSet.o


# Ο βασικός κορμός του Makefile
include ../common.mk